####Installing httpd or apache2 by checking redhat or debian based systems using playbook.

---
- name: Installing and configuring httpd or apache2
  hosts: all
  become: true

  tasks: 
    - name: Installing httpd on RedHat
      yum: 
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Starting httpd service on RedHat
      service: 
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: Installing apache2 on Debian
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Starting apache2 service on Debian
      service: 
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: Copy index.html file
      copy: 
        src: /home/ansibleadmin/index.html
        dest: /var/www/html/index.html
        mode: '0644' 


###using notify for same
---
- name: This playbook installs httpd or apache2
  hosts: all
  become: true

  tasks:
    - name: Installing httpd on RedHat
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"
      notify: Start httpd service

    - name: Installing apache2 on Debian
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
      notify: Start apache2 service

  handlers:
    - name: Start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: Start apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
