---
- name: Installing tomcat using playbook
  hosts: webservers
  become: true

  tasks: 
    - name: Installing java on RedHat
      yum: 
          name: java
          state: installed
      when: ansible_os_family == "RedHat"

      - name: Installing java on Debian
        apt: 
          name: default-jdk
          state: present
        when: ansible_os_family == "Debian"

      - name: Download Tomcat
        get_url: 
          url: "https://downloads.apache.org/tomcat/tomcat-8/v8.5.65/bin/apache-tomcat-8.5.65.tar.gz"
          dest: /opt

      - name: Extract Tomcat
        unarchive: 
          src: /opt/apache-tomcat-8.5.65.tar.gz
          dest: /opt
          remote_src: yes

      - name: Add executable permissions
        file: 
          path: /opt/apache-tomcat-8.5.65.tar.gz
          mode: 0777    
      
      - name: Start tomcat service
        shell: nohup ./startup.sh
        args:
          chdir: /opt/apache-tomcat-8.5.65/bin

