####Playbook to copy a file

---
- name: Playbook to copy a file
  hosts: all
  become: true
  tasks:
  - name: Copy a file
    copy: 
      src: /home/ansibleadmin/index.html
      dest: /home/ansibleadmin/index.html
      mode: '0666'
      owner: anush
      group: anush


####To create a directory

----
- name: This playbook is used to create directory
  hosts: all
  become: true
  tasks:
    - name: Create a directory
      file: 
        path: /home/ansibleadmin/dir1
        state: directory
        mode: '0755'  # Optional: Set permissions for the directory


####To delete a directory      

---
- name: This playbook is to delete an earlier created directory
  hosts: all
  become: true
  tasks:
    - name: Delete a directory
      file:
        path: /home/ansibleadmin/dir1
        state: absent
        

####To create a file          

---
- name: This playbook is used to create a file
  hosts: webservers
  become: true
  tasks:
    - name: Create a file
      file:
        path: /home/ansibleadmin/file
        state: touch
    
