##Installing httpd 

 ---
- name: Install and start httpd
  hosts: all
  become: true
  tasks:

    - name: Install httpd
      yum:
        name: httpd
        state: installed  # this line can be ignored as system consider installation by default . can use 'present' instead of installed.

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
       


##Unstalling httpd     

    - name: stopping httpd
      service:
        name: httpd
        state: stopped

    - name: uninstalling httpd
       yum:
        name: httpd
        state: removed

---
- name: Uninstall httpd using playbook
  hosts: all
  become: true
  tasks:

    - name: Stop httpd service
      service:
        name: httpd
        state: stopped

    - name: Uninstall httpd
      yum:
        name: httpd
        state: absent ## you have to mention this as this is not default nature . can use 'removed' instead of absent
      
       
