##Installing httpd 
---
- name: httpd installation using playbook
  hosts: all
  become: true
  tasks:

    - name: install httpd
      yum:
        name: httpd
        state: present ## this can be 

    - name: start httpd
      service:
        name: httpd
        state: started


##Unstalling httpd     


---
- name: httpd Uninstallation using playbook
  hosts: all
  become: true
  tasks:

    - name: stopping httpd
      service:
        name: httpd
        state: stopped

    - name: uninstalling httpd
       yum:
        name: httpd
        state: removed
       